[package]
name = "kevin-api"
description = "HTTP API interface crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
kevin-domain.workspace = true
kevin-config.workspace = true
kevin-orchestrator = { workspace = true, optional = true }

[features]
default = ["server"]
server = ["dep:kevin-orchestrator"]
client = []
